
pool: new-agent
  

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'


