pool: new-agent



steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: | 
      dotnet build $(Build.SourcesDirectory)/backend/backend.csproj -c Release -o /Users/emresavan/export
      dotnet publish $(Build.SourcesDirectory)/backend/backend.csproj -c Release -o /Users/emresavan/export /p:UseAppHost=false
